# Builds on commit

name: On commit

pool:
  vmImage: 'VS2017-Win2016'

trigger:
  batch: true

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: FbonizziMonoGame build
    variables:
      solution: 'FbonizziMonoGame.sln'

    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
